nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.1.cjs

enableGlobalCache: false

packageExtensions:
  "@docsearch/react@*":
    peerDependencies:
      "@algolia/client-search": "*"
      "algoliasearch": "*"
  "@algolia/autocomplete-core@*":
    peerDependencies:
      "@algolia/client-search": "*"
      "algoliasearch": "*"
  "@algolia/autocomplete-plugin-algolia-insights@*":
    peerDependencies:
      "@algolia/client-search": "*"
      "algoliasearch": "*"
      "search-insights": "*"
  "recma-jsx@*":
    peerDependencies:
      "acorn": "*"
  "pliny@*":
    peerDependencies:
      "react": "^18.0.0"
      "react-dom": "^18.0.0"
  "react-virtual@*":
    peerDependencies:
      "react": "^18.0.0"
      "react-dom": "^18.0.0"
